// Code generated by MCHP Chatbot
/*******************************************************************************
  Main Source File

  Company:
    Microchip Technology Inc.

  File Name:
    main.c

  Summary:
    This file contains the "main" function for a project.

  Description:
    This file contains the "main" function for a project.  The
    "main" function calls the "SYS_Initialize" function to initialize the state
    machines of all modules in the system
 *******************************************************************************/

// *****************************************************************************
// *****************************************************************************
// Section: Included Files
// *****************************************************************************
// *****************************************************************************

#include <stddef.h>                     // Defines NULL
#include <stdbool.h>                    // Defines true
#include <stdlib.h>                     // Defines EXIT_FAILURE
#include "definitions.h"                // SYS function prototypes

// *****************************************************************************
// *****************************************************************************
// Section: Main Entry Point
// *****************************************************************************
// *****************************************************************************

int main ( void )
{
    /* Initialize all modules */
    SYS_Initialize ( NULL );

    // Start SYSTICK timer
    SYSTICK_TimerStart();

    while ( true )
    {
        /* Stream LED sequence: Negative logic (Clear = ON, Set = OFF) */

        // LED1 ON, others OFF
        LED1_Clear(); LED2_Set(); LED3_Set(); LED4_Set();
        SYSTICK_DelayMs(500);

        // LED2 ON, others OFF
        LED1_Set(); LED2_Clear(); LED3_Set(); LED4_Set();
        SYSTICK_DelayMs(500);

        // LED3 ON, others OFF
        LED1_Set(); LED2_Set(); LED3_Clear(); LED4_Set();
        SYSTICK_DelayMs(500);

        // LED4 ON, others OFF
        LED1_Set(); LED2_Set(); LED3_Set(); LED4_Clear();
        SYSTICK_DelayMs(500);

        SYS_Tasks();    // Keep MPLAB Harmony state machine
    }

    /* Execution should not come here during normal operation */
    return ( EXIT_FAILURE );
}

/*******************************************************************************
 End of File
*/
